raiden: monkey patch asyncio and aioice
For asyncio, it could happen that the transport's sendto() method is
invoked after the transport was closed. Closing the transport sets the
_sock attribute to None, which then causes the following exception:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
    AttributeError: 'NoneType' object has no attribute 'sendto'

So just check if we're closed before doing anything, similarly to what we already
do in other methods.

For aioice, it could happen that the local candidate is not set when we
enter connection_lost:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.9/asyncio/selector_events.py", line 736, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/home/ivan/venv-3.9/lib/python3.9/site-packages/aioice/ice.py", line 173, in connection_lost
        self.receiver.data_received(None, self.local_candidate.component)
    AttributeError: 'NoneType' object has no attribute 'component'