Fix exception thrown due to MockRaidenService not stopping properly
Before this fix all tests that were instantiating Mock Raiden services
had a warning of uncaught and ignored exception in the logs during teardown:

```
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fed6e5fecb0>
Traceback (most recent call last):
  File "/home/lefteris/ew/raiden/raiden/storage/sqlite.py", line 731, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function SQLiteStorage.__del__ at 0x7fed6e5fecb0>
Traceback (most recent call last):
  File "/home/lefteris/ew/raiden/raiden/storage/sqlite.py", line 731, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
```

Adding a proper `stop()` of the service's WAL storage fixes that.