alarm task stopped before filter uninstall
RaidenService had a race among the alarm task and the filter removal,
that allowed the filter to be uninstall before the next poll callback
was
executed, resulting in exceptions like the following:

JSONRPCClientReplyError: filter not found

This change adds synchronization, requiring the alarm task to
completely stop before the events are removed.