Improve typing in `tools`
I did this because I got the following linting error from
.circleci/enforce_decreasing_lint_errors.sh in CI:

```
> tools/gas_cost_measures.py:179: error: Argument "additional_hash" to
"pack_balance_proof" has incompatible type "bytes"; expected
"AdditionalHash"
> tools/startcluster.py:40: error: Argument "rpc_port" to
"EthNodeDescription" has incompatible type "int"; expected "Port"
> tools/startcluster.py:40: error: Argument "p2p_port" to
"EthNodeDescription" has incompatible type "int"; expected "Port"
> tools/startcluster.py:55: error: Argument "chain_id" to
"GenesisDescription" has incompatible type "int"; expected "ChainID"
> tools/startcluster.py:60: error: Argument "verbosity" to
"run_private_blockchain" has incompatible type "int"; expected "str"
> tools/startcluster.py:60: error: Need type annotation for
'private_chain'
1a8
> tools/transfer_eth.py:26: error: Argument 2 to "JSONRPCClient" has
incompatible type "Optional[PrivateKey]"; expected "bytes"
```

I don't know why mypy actually checked these (the functions were
untyped), but fixing the typing errors is helpful anyway and will
hopefully resolve the CI problem.