Remove ChannelID type annotation on some other IDs
This commit removes error messages from
`mypy raiden/transfer/mediated_transfer/target.py --ignore-missing-imports`
namely,
```
> raiden/storage/sqlite.py:226: error: Argument "event_identifier" to "EventRecord" has incompatible type "int"; expected "ChannelID"
> raiden/storage/sqlite.py:273: error: Argument "state_change_identifier" to "StateChangeRecord" has incompatible type "int"; expected "ChannelID"
```

[no ci integration]